[package]
name = "pbr-gpu"
version = "0.1.0"
edition = "2024"

[dependencies]
bytemuck = "1.24.0"
glam = { version = "0.30.9", features = ["bytemuck"] }
image = "0.25.9"
ordered-float = "5.1.0"
pollster = "0.4.0"
wgpu = "28.0.0"
